### ISSUE TITLE
Could you show the benchmark comparison result?

### ISSUE THREAD

**Issue by GF-Huang** [jonorogers/SpanDex#1]
I remember I had test a wrapper of `BinaryPrimitives` will a bit slower than the original `BinaryPrimitives`.

**Comment by jonorogers** [comment]
Sure, I've added it to the readme. Using SpanDex does add a bit of overhead over just bitconverter; and interestingly just doing the conversion yourself is twice as fast as bitconverter..

But then; neither option gives you the convenience of not needing to keep track of where you're upto in a span, either reading or writing.. which was why this library was written..
